/**
 * uid
 *
 * Generates new unique identifiers, which are just integers guaranteed to
 * never repeat for the duration of the program.
 *
 * Note that these are _not_ **uuids**, which have a spec that must be followed.
 *
 * Exports an object with a few stored functions.
 *
 * @method make - returns a new, unused integer for an id
 * @method exists - returns boolean, true if that id has been generated by a previous make call
 * @method reset - makes next uid 0 again.  This could result in non-unique ids, since it doesn't unset things keeping track of the uid, so use with caution
 */
let uidCount = 0;

let makeUid = function () {
	return uidCount++;
};
let uidExists = function (id) {
	return id < uidCount;
};
let reset = function () {
	uidCount = 0;
};

module.exports = {
	make: makeUid,
	exists: uidExists,
	reset: reset
};
